# Generated by Django 4.0.3 on 2022-07-20 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Coder', '0004_alter_curso_options_entregable_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Coder.estudiante'),
        ),
    ]
